### ISSUE TITLE
Proposed new entry: Customized printer for exposed C++ classes

### ISSUE THREAD

**Issue by schalkdaniel** [RcppCore/rcpp-gallery#105]
Hi,

Dirk suggests to write an entry about customizing a printer for an exposed `C++` class using the Rcpp modules ([see here](https://stackoverflow.com/questions/47871377/print-generic-for-rcpp-class/47873455#47873455)). 

I have wrote something [here](https://gist.github.com/schalkdaniel/71c054c01408e0803c6960e23341c408). Any suggestions on how to improve the Rmd are very much appreciated.

Sincerely, 
Daniel

**Comment by eddelbuettel** [comment]
Can close as this went live :)
