### ISSUE TITLE
Article on RcppArrayFire?

### ISSUE THREAD

**Issue by rstub** [RcppCore/rcpp-gallery#108]
If you are interested, I could contribute an article on RcppArrayFire, e.g. along the lines of http://www.daqana.org/rcpparrayfire/articles/RcppArrayFire.html. Or as an extension of the recent article on put options using something like
```
#include <RcppArrayFire.h>

// [[Rcpp::depends(RcppArrayFire)]]

using af::array;
using af::log;
using af::erfc;
using std::sqrt;
using std::exp;

array normcdf(array x) {
  return erfc(-x / sqrt(2.0)) / 2.0;
}

// [[Rcpp::export]]
array put_option_pricer_af(RcppArrayFire::typed_array<f32> s, double k, double r, double y, double t, double sigma) {
  
  array d1 = (log(s / k) + (r - y + sigma * sigma / 2.0) * t) / (sigma * sqrt(t));
  array d2 = d1 - sigma * sqrt(t);
  
  return normcdf(-d2) * k * exp(-r * t) - s * exp(-y * t) * normcdf(-d1); 
}
```
Caveat is of course that it complicates building the gallery due to dependence on the [ArrayFire library](https://arrayfire.com).

**Comment by eddelbuettel** [comment]
That is a bit of a concern. "Effectively" I run make here, and the Jekyll backend creates the page that will be rendered using the knitr hooks.  We could of course a) mock that or b) ensure I have ArrayFire.  But it is a bit more work...

So call it "interested in principle, details to be sorted out" which may be a roadblock.

**Comment by eddelbuettel** [comment]
Ok, I am set up:

```
R> Rcpp::sourceCpp("/tmp/arrayfireex.cpp")
R> put_option_pricer_af(seq(50,70), 60, 0.02, 0.01, 1, 0.05)
 [1] 9.309618950 8.320249557 7.332633495 6.350021839 5.379636765 4.434770107 3.536008835 2.709769487
 [9] 1.983613491 1.379329920 0.906861544 0.561682820 0.326888025 0.178463712 0.091329783 0.043805983
[17] 0.019703230 0.008317218 0.003298973 0.001231334 0.000433151
R> 
```

**Comment by rstub** [comment]
That was fast :-) I will go forward with the article then. My suggestion would be to follow the vignette but use the put option instead of the matrix multiplication as example. Ok?

**Comment by eddelbuettel** [comment]
Any example is fine, you don't have to use the put example.  Whatever you think makes the most compelling case.
