### ISSUE TITLE
Strings and Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/rcpp-gallery#11]
I wrote up a small article on using Rcpp to go back and forth between CharacterVector's and std::vector< std::string >s. The format is in .Rmd

https://gist.github.com/4488118

**Comment by eddelbuettel** [comment]
Hi Kevin,

That looks good.   But you can even have Rcpp attributes take care of the as<>() and wrap() -- try another variant

   // [[Rcpp::export]]
   std::vector<string>  foo(std::vector<string> ) {
       // as before...
   }

That will make it even longer so maybe worth shortening somewhere....

Dirk

**Comment by jjallaire** [comment]
Agreed, thanks very much for the contribution!

One change I'd like to see before we merge in the article: remove the "using
namespace std". We don't do this in our other articles for an important
reason: Rcpp attributes require fully qualified types in signatures (with
the exception of the Rcpp namespace) so if you want to return or take a
vector you need to use std::vector (as Dirk suggests below)

J.J.

**Comment by kevinushey** [comment]
I hadn't realized Rcpp attributes would even handle return types -- that's pretty amazing!

I made a new gist with better use of the Rcpp attributes, and also removed the 'using namespace std;' calls. 

https://gist.github.com/4488280

Thanks!
-Kevin

**Comment by eddelbuettel** [comment]
Yep, that was good old magic (courtesy of Romain) to wrap std::FOO for various foo as well. Inline supported that for a long time too; Attributes "just" sits on top (and does its own layer of magic thanks to JJ).

This looks good. I have an R/Finance mtg later and need to actually blog about this all but maybe JJ can blend the piece in.

So welcome to our next contributing author :)

Dirk

**Comment by jjallaire** [comment]
Just published: http://gallery.rcpp.org/articles/strings_with_rcpp/

Thanks again!

J.J.
