### ISSUE TITLE
Add Gallery Post on Rcpp equivalent of stop(..., call.=FALSE)

### ISSUE THREAD

**Issue by michaelweylandt** [RcppCore/rcpp-gallery#110]
Here's the Rcpp gallery post I promised in RcppCore/Rcpp#828 on call-stack-free versions of `Rcpp::stop` and `Rcpp::warning`: 

https://gist.github.com/michaelweylandt/d0c53047229a5351affdb6c163b27cbc

**Comment by eddelbuettel** [comment]
Nice. Did very minor edits and will commit.  Or do you want to via a PR?

**Comment by michaelweylandt** [comment]
No desire to do a formal PR -- go ahead and commit.
