### ISSUE TITLE
Doxygen documentation in R package 

### ISSUE THREAD

**Issue by mlysy** [RcppCore/rcpp-gallery#112]
I am working on a package called [**rdoxygen**](https://github.com/nevrome/rdoxygen) (lead by @nevrome), of which the purpose is to easily add Doxygen documentation for the C++ code to the R package containing it.  Among other features, the package allows the Doxygen docs to be wrapped in an R vignette, so as to be easily accessible by the package users.

We believe these functionalities would be useful to many R/C++ package developers, and thus would like to contribute a small tutorial to Rcpp Gallery.  Would you be open to such a contribution, even though the article isn't exactly about Rcpp?

**Comment by eddelbuettel** [comment]
Sounds fair, especially if you can motivate it with some Rcpp context.

We don't really talk much about packages and vignettes there though.

**Comment by mlysy** [comment]
Thanks for the feedback. We will motivate with Rcpp if attempting to post a tutorial here.
