### ISSUE TITLE
remove outdated sparse matrix examples

### ISSUE THREAD

**Issue by conradsnicta** [RcppCore/rcpp-gallery#113]
Sparse matrix examples from 2012 and 2013 (links below) are outdated and should probably be removed.

http://gallery.rcpp.org/articles/armadillo-sparse-matrix/
https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2012-12-25-armadillo-sparse-matrix.cpp

http://gallery.rcpp.org/articles/as-and-wrap-for-sparse-matrices/
https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2013-08-05-as-and-wrap-for-sparse-matrices.cpp

The above rcpp-gallery examples have several problems. They use internal (non-public) armadillo functionality that is marked as deprecated, ie. arma::memory::acquire_chunked().  This function will be removed.  The examples also directly create an armadillo sparse matrix by poking the SpMat arrays without taking into account the state of the internal cache. This is dangerous, as the example promotes dangerous use (ie. people may simply copy and paste the code, and then modify it without thinking).

To construct a sparse matrix from existing [CSC](https://en.wikipedia.org/wiki/Sparse_matrix) arrays, it's far safer and simpler to use the appropriate [sparse matrix constructor](http://arma.sourceforge.net/docs.html#SpMat):

    sp_mat(rowind, colptr, values, n_rows, n_cols)

**Comment by eddelbuettel** [comment]
I will try to make time to take a look.  In general, we have not retired pages. The idea is to improve them, and as such, pull requests with improved content would make it easier to do that.

**Comment by binxiangni** [comment]
```
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;

// [[Rcpp::export]]
void convertSparse(S4 mat) {
  IntegerVector dims = mat.slot("Dim");
  arma::urowvec i = Rcpp::as<arma::urowvec>(mat.slot("i"));
  arma::urowvec p = Rcpp::as<arma::urowvec>(mat.slot("p"));     
  arma::vec x     = Rcpp::as<arma::vec>(mat.slot("x"));
  
  int nrow = dims[0], ncol = dims[1];
  arma::sp_mat res(i, p, x, nrow, ncol);
  Rcout << "SpMat res:\n" << res << std::endl;
}
```

Just used the constructor mentioned by @conradsnicta to rewrite an example for the first article. Maybe we could use it to replace the outdated example in the first article.

**Comment by eddelbuettel** [comment]
Ok, finally had  a chance to run over there and look.  That is definitely a better 'body' for the `convertSparse(S4 mat)` function.    We _could_ keep the old one as a "by the way, this is how we did it before" case.    If we kept it on this page, then we could shorten the other page with `as<>` and `wrap()` and just refer back to this one in a short half-sentence or so.

But we should probably also add a 'create from R' example highlighting your work, no?

**Comment by binxiangni** [comment]
Yeah, we can still keep the R example from previous example. And I am still thinking how I can modify the second example. It seems that I need to include most of the code in the `as<>()` I wrote last summer.

**Comment by eddelbuettel** [comment]
Don't go overboard. Maybe just sketch something here in a few bullet points first.

Good stuff -- thanks again to @conradsnicta for raising this and to you for looking into it.

**Comment by binxiangni** [comment]
Just extract a piece of source code of as<>() and wrap() to replace the outdated second example.

```
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;

namespace Rcpp {

    // converts an SEXP object from R which was created as a sparse
    // matrix via the Matrix package) into an Armadillo sp_mat matrix
    //
    // NB: called as_() here as a similar method is already in the
    //     RcppArmadillo sources
    //
    
    // The following as_() only applies to dgCMatrix. 
    //For other types of sparse matrix conversion, you might want to check the source code of RcppArmadillo.
    template <typename T> arma::SpMat<T> as_(SEXP sx) {
      
      // Rcpp representation of template type
      const int RTYPE = Rcpp::traits::r_sexptype_traits<T>::rtype;
      
      // instantiate S4 object with the sparse matrix passed in
      S4 mat(sx);  
      IntegerVector dims = mat.slot("Dim");
      IntegerVector i = mat.slot("i");
      IntegerVector p = mat.slot("p");     
      Vector<RTYPE> x = mat.slot("x");
      
      // create sp_mat object of appropriate size
      arma::SpMat<T> res(dims[0], dims[1]);
      
      // Making space for the elements
      res.mem_resize(static_cast<unsigned>(x.size()));
      
      // In order to access the internal arrays of the SpMat class
      res.sync();
      
      // Copying elements
      std::copy(i.begin(), i.end(), arma::access::rwp(res.row_indices));
      std::copy(p.begin(), p.end(), arma::access::rwp(res.col_ptrs));
      std::copy(x.begin(), x.end(), arma::access::rwp(res.values));
      
      return res;
    }

}
```
Here I just list the conversion of dgCMatrix. And I'll ignore the conversion of other types of sparse matrix here and might add a link to source code for users who might be interested.

```
namespace Rcpp {

    // convert an Armadillo sp_mat into a corresponding R sparse matrix
    // we copy to STL vectors as the Matrix package expects vectors whereas the
    // default wrap in Armadillo returns matrix with one row (or col) 
    //
    // NB: called wrap_() here as a similar method is already in the 
    //     RcppArmadillo sources
    //
    template <typename T> SEXP wrap_(const arma::SpMat<T>& sm) {
      const int  RTYPE = Rcpp::traits::r_sexptype_traits<T>::rtype;
      
      // In order to update internal state of SpMat object
      sm.sync();
      IntegerVector dim = IntegerVector::create( sm.n_rows, sm.n_cols );
      
      // copy the data into R objects
      Vector<RTYPE> x(sm.values, sm.values + sm.n_nonzero ) ;
      IntegerVector i(sm.row_indices, sm.row_indices + sm.n_nonzero);
      IntegerVector p(sm.col_ptrs, sm.col_ptrs + sm.n_cols+1 ) ;
      
      std::string klass = "dgCMatrix";
    
      S4 s(klass);
      s.slot("i")   = i;
      s.slot("p")   = p;
      s.slot("x")   = x;
      s.slot("Dim") = dim;
      return s;
    }

}
```

Here I also just wrap the result of RcppArmadillo to a dgCMatrix. That's the only type passed from RcppArmadillo to R.

**Comment by eddelbuettel** [comment]
Yes, a link to the source where the current/better implementation is good. Maybe a usage example of the newer high-level code?   And then keep these `as_()` and `wrap_()` which explain with the one concrete example (ie `dgCMatrix`) what is going on.

**Comment by eddelbuettel** [comment]
@conradsnicta Have a look now -- @binxiangni kindly overhauled these, and I just merged and did a small amount of polish at the edges:
- http://gallery.rcpp.org/articles/armadillo-sparse-matrix/
- http://gallery.rcpp.org/articles/as-and-wrap-for-sparse-matrices/

**Comment by conradsnicta** [comment]
@eddelbuettel - i'll take a look in a few days; currently snowed under with deadlines

**Comment by eddelbuettel** [comment]
Sure thing, and no rush; I mostly circled back only because it had taken us a jolly moment as well.

**Comment by conradsnicta** [comment]
@binxiangni - I recommend placing the call to `sync()` before `mem_resize()`, ie. change the order of `res.mem_resize(static_cast<unsigned>(x.size()))` and `res.sync()`.

**Comment by eddelbuettel** [comment]
Thanks -- done in e3c372c

**Comment by eddelbuettel** [comment]
This can now be closed.
