### ISSUE TITLE
Half of an article missing

### ISSUE THREAD

**Issue by Enchufa2** [RcppCore/rcpp-gallery#117]
It seems that cdb37c6 wiped out clean half of [this article](https://gallery.rcpp.org/articles/passing-cpp-function-pointers-rcppxptrutils/).

**Comment by eddelbuettel** [comment]
Strange.  Maybe a Jekyll side effect.  We it in the change to the `_posts/` file but not to the `src/`.

I'll look into restoring it on the weekend.

**Comment by eddelbuettel** [comment]
Weird.  The content is actually still there:  https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2017-08-04-passing-cpp-function-pointers-rcppxptrutils.Rmd

And the change to the Rmd, as seen some 90% or so down the commit you reference, was one char.

Seeme like Jekyll tricked me.  I am sure we'll get in back.

**Comment by eddelbuettel** [comment]
Should be better now.

**Comment by Enchufa2** [comment]
Thanks, LGTM.

**Comment by eddelbuettel** [comment]
Ok, closing then.  Thanks for the heads-up!
