### ISSUE TITLE
gist for example with update of 2013-07-13-dmvnorm_arma.Rmd

### ISSUE THREAD

**Issue by boennecd** [RcppCore/rcpp-gallery#123]
Here is an updated version of [2013-07-13-dmvnorm_arma.Rmd](https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2013-07-13-dmvnorm_arma.Rmd): https://gist.github.com/boennecd/db36747096e0d8a996a06e571f181ede

`dmvnrm_arma` now yields a reduction in computation time relative to `dMvn` of ~44% compared to ~10% before and `dmvnorm_arma`  yields a reduction in computation time of ~22% compared to an __increase__ of ~97% before.

I have also added a remark about the numerical stability.

**Comment by eddelbuettel** [comment]
Do you want to maybe add that as a full-fledge update to the original post?  We have examples of updated posts.  You could probably make yourself third author and could of course try to reach out to the two original ones. Interested?

Also a little hard to see _what_ you changed as the gist has no diff to the original.  

Or is mostly a 'rebuilt & reran' that is faster now because Armadillo does more OpenMP etc pp?  Still good to update, and good to give credit where due ...

**Comment by boennecd** [comment]
Thanks! 

> Do you want to maybe add that as a full-fledge update to the original post? We have examples of updated posts. You could probably make yourself third author and could of course try to reach out to the two original ones. Interested?

Sure, I gather I should reach out to the two authors first though. 

> Also a little hard to see what you changed as the gist has no diff to the original.

In all functions, I used `const &` to avoid copies. This reduced the computation time some. 

In `dmvnrm_arma[_mc]` I

1. moved the declaration of `arma::vec z` outside of the loop to avoid repeated allocations of memory (if I am correct)  here: https://github.com/RcppCore/rcpp-gallery/blob/676844d0c439a5b7e127a64eff631d0ad7d8c576/src/2013-07-13-dmvnorm_arma.Rmd#L67
2. got rid of the `arma::trans` in the same line. I am not sure whether that had any effect.
3. replaced `arma::sum` with `arma::dot` here: https://github.com/RcppCore/rcpp-gallery/blob/676844d0c439a5b7e127a64eff631d0ad7d8c576/src/2013-07-13-dmvnorm_arma.Rmd#L68
4. did other minor things which I presume only had a minor effect.

`Mahalanobis` is almost entirely re-written. It now uses `each_col` and `for_each` which may be run in parallel using `OpenMP` if I recall correctly. Moreover, there is only one matrix assignment now if I am correct.

> Or is mostly a 'rebuilt & reran' that is faster now because Armadillo does more OpenMP etc pp?

All the computation time differences that I state is run on my current setup using the same version of `RcppArmadillo`.

**Comment by eddelbuettel** [comment]
From the top of my head and without time for deeper testing:

0. Adding `const &` is nice and good practice. Due to the nature of `SEXP` it is unlikely to affect real change.  We did some benchmarking (still below `inst/examples` in the package) when we made the change.
1.  The compiler should be smart enough here too.  And a simple declaration does zero allocation.
2.  No idea
3.  That may matter.
4.  Sure :)

**Comment by boennecd** [comment]
A minor comment to 

> 1. The compiler should be smart enough here too. And a simple declaration does zero allocation.

Adding 

```cpp
// [[Rcpp::depends("RcppArmadillo")]]
// [[Rcpp::export]]
arma::vec dmvnrm_arma01(arma::mat const &x,  
                        arma::rowvec const &mean,  
                        arma::mat const &sigma, 
                        bool logd = false) { 
    int n = x.n_rows;
    int xdim = x.n_cols;
    arma::vec out(n);
    arma::mat const rooti = arma::inv(trimatu(arma::chol(sigma)));
    double const rootisum = arma::sum(log(rooti.diag())), 
                constants = -xdim/2.0 * log2pi, 
              other_terms = rootisum + constants;
    
    for (int i=0; i < n; i++) {
        arma::rowvec z = (x.row(i) - mean) * rooti;    
        out(i)         = other_terms - 0.5 * arma::dot(z, z);     
    }  
      
    if (logd == false)
        out = exp(out);
    return(out);
}
```

then running

```r
benchmark(mvtnorm::dmvnorm(X,means,sigma,log=F), 
          dmvnorm_arma(X,means,sigma,F), 
          dmvnrm_arma(X,means,sigma,F) ,
          dmvnrm_arma01(X,means,sigma,F),
          dmvnrm_arma_mc(X,means,sigma,F,cores), 
          dMvn(X,means,sigma),
          order="relative", replications=100)[,1:4]
##                                         test replications elapsed relative
## 5  dmvnrm_arma_mc(X, means, sigma, F, cores)          100   2.100    1.000
## 3            dmvnrm_arma(X, means, sigma, F)          100   7.695    3.664
## 4          dmvnrm_arma01(X, means, sigma, F)          100   8.132    3.872
## ...
```

which shows that it does seem to matter. I guess it has to do with the assignment operator and the temporary object that is on the right hand side of the assignment. This is with 

```
gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
```

and `-O3`.

**Comment by boennecd** [comment]
I have created a pull request at https://github.com/RcppCore/rcpp-gallery/pull/124.

**Comment by eddelbuettel** [comment]
Now merged -- thanks again!
