### ISSUE TITLE
trivial typo

### ISSUE THREAD

**Issue by bbolker** [RcppCore/rcpp-gallery#140]
"Pythagoras" is misspelled here: https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2012-12-20-simulating-pi.cpp#L16

Do you want a pull request?

**Comment by eddelbuettel** [comment]
Thanks for catching that eight year old typo!   

I'll take of it from here here, we have a bit of an old / home-grown jekyll setup so a pull request in just the file you see won't propagate automagically.

**Comment by eddelbuettel** [comment]
Oh, I lied -- 2012-12-20.  One of the very first page and hence almost a decade old.  Wow.

Just committed the fix in https://github.com/RcppCore/rcpp-gallery/commit/e001e17630c33739b331f12d692fc14cad58cb04 and as I forgot to add a 'closes #140' there I will close now by hand.  Thanks again!
