### ISSUE TITLE
'finance' tag broken?

### ISSUE THREAD

**Issue by bbolker** [RcppCore/rcpp-gallery#144]
When I click on the "finance" tag heading it tries this URL https://gallery.rcpp.org/tags/finance/, which gives me a 404 error. Other tags (including equally small/obscure ones) seem to work ... ? (Using the search bar to look for "finance" gives me 3 hits.)

**Comment by eddelbuettel** [comment]
Hmpf.  The font size implies a single post, judging from others, so I may have deleted a (single) post exhibiting the tag, or edited a post and removed it.  The way `jekyll` adds to the gh-pages branch / docs directory may not remove stale entries. 
My local repo (which is where 'prod' happens) has no entry for 'finance' in the tags directory but I do see [it in this story](https://gallery.rcpp.org/articles/gerber-statistic/) or more specifically [its source](https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/src/2016-05-26-gerber-statistic.Rmd).  We may just have to live with this unless someone sits down and debugs `jekyll`.

**Comment by bbolker** [comment]
OK, thanks.
