### ISSUE TITLE
Make your own 'apply' functions for matrices

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/rcpp-gallery#15]
Hi guys,

I made an interesting example showing how one might use 'sourceCpp' in a similar manner to 'inline' to generate C++ apply functions on the fly.

https://gist.github.com/4567244

Also, something that was a bit surprising -- it seems like it may be faster to perform a column apply on the transpose of a matrix, rather than a row apply. At least for the test cases I run, on my machine, etc... but I was surprised!

Let me know what you think,
-Kevin

**Comment by eddelbuettel** [comment]
Hi Kevin,
Two quick points:  
a) can't you use cppFunction() over a string in your rcpp_apply_generator?  
b) I think I made the very point of colMeans-of-transpose to you in email on the list, it is a consequence of col-major storage
So I think this is good, but I feel it could better if reworked.  Maybe shortened and put into two pieces?
Thanks,  Dirk

**Comment by kevinushey** [comment]
Hi Dirk,

re: a), I'm not sure exactly how you mean -- isn't cppFunction only for defining single functions? Whereas I'm embedding a function in a source file with multiple functions. I suppose I could combine it all into one big function with a bunch of 'if' statements but I feel like this version is perhaps preferable... or am I misunderstanding how it might be used?

I agree that it's too long at this point -- I'll try to rework it.

**Comment by eddelbuettel** [comment]
Hi Kevin,
I did not look that closely, but just about anything you do involving getting tempfiles strikes me as wrong -- that is what sourceCpp() et al (and cppFunction()).  Maybe you can explain what you want in a simpler smaller example which we try to address (either in a  small piece here or on the rcpp-devel list).
I'm sure we'll get something nice out of this.
Dirk

**Comment by kevinushey** [comment]
Sure. The ultimate goal would be something like, say as a simple example I wanted to calculate the `sd` over columns of a matrix `x`, I would write (this or something similar):

```
rcpp_apply(x, 2, "return sd(x);" )
```

It would provide a nice means for prototyping row/column apply functions in an R session. Even better, if we could define a whole function in there, in terms of some variable `x` (example with the sample variance):

```
rcpp_apply(x, 2, "
  double out = 0; 
  double m = mean(x);
  double N = x.size();
  for( int i=0; i < N; i++ ) { 
    out += (x[i]-m) * (x[i]-m);
  }
  return out / ( N-1 );
  "
```

but I'm not sure what the best way of wrapping something like this up would be. But the ultimate point would be: defining a C++ function that could take advantage of any other C++ libraries / includes / dependencies through a simple R interface, specifically for these `apply` problems. And this would be faster than calling `apply(x, 2, cppFunction(...) )` as R's `apply` would still be slow.

Thanks,
-Kevin

**Comment by eddelbuettel** [comment]
I understand better now :)  JJ also waved a cluebat.  I still think that cppFunction() and using a function pointer / external pointer would be much cleaner though. I have done that in RcppDE for pointers to essentially arbitrary objective functions -- including compiled ones. 

But we can get it to work first.

Dirk
