### ISSUE TITLE
BOOST_FOREACH and Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/rcpp-gallery#18]
Hi guys,

I made a short example showing how we might use BOOST_FOREACH with Rcpp.

https://gist.github.com/4677510

Let me know what you think,

-Kevin

**Comment by eddelbuettel** [comment]
Nice,  Though I am a little ALLERGIC_TO_UPPERCASE_SHOUTING, see my SO question at http://stackoverflow.com/questions/1268541/boost-foreach-is-there-a-trick-to-avoid-the-all-caps-spelling

On more substantive matters, should we a) differentiate this for foreach in C++11 or not [needing C++11 may be a plus as CRAN blocks C++11] and the b) the other 'functional sweep approaches' in the gallery [ don't have to but thought I'd mention... ]

**Comment by eddelbuettel** [comment]
Maybe if you add a paragraph or sentence how this influenced C++11 foreach (http://stackoverflow.com/questions/7562356/c11-foreach-syntax-and-custom-iterator) ?

**Comment by kevinushey** [comment]
Hey Dirk,

I added a little bit on why it might be preferred to std::for_each or std::transform, CRAN vs. C++11, C++11's foreach construct, a little #define header (I agree, the all-caps is ugly and for small use cases #define won't be a problem), and then gave a small blurb about how it works with a link to the SO article.

Thanks!
-Kevin
