### ISSUE TITLE
Feedback channel

### ISSUE THREAD

**Issue by kenahoo** [RcppCore/rcpp-gallery#20]
The new Rcpp gallery stuff is very cool.  But I don't see any way to provide feedback on articles, either directly to the author or as a comment.  Is that something that could be added?  It looks like the only channel available is to fork it & submit a pull request, but there's no mention of that, nor facilitating link, that I can see.

**Comment by eddelbuettel** [comment]
I think this got closed by your patch.

**Comment by jjallaire** [comment]
yes it did!

J

On Wed, Feb 27, 2013 at 8:15 AM, Dirk Eddelbuettel <notifications@github.com
