### ISSUE TITLE
Fast factor generation with Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/rcpp-gallery#22]
Hi guys,

I put together an article on faster factor generation with Rcpp, as well as an example inspired by R's tapply. Take a look:

https://gist.github.com/cdrv/5045531

Thanks!
-Kevin

**Comment by jjallaire** [comment]
Looks great! I've created a pull request so that Dirk can review and merge assuming everything looks good to him as ell.

**Comment by jjallaire** [comment]
Dirk merged the pull request so this is now published....thanks!
