### ISSUE TITLE
Dynamic Wrapping and Recursion with Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/rcpp-gallery#26]
Hi guys,

I put together an example of using R's C API together with Rcpp to recurse through lists, and dynamically wrap R objects after determining their internal R type. It's a question that's been occasionally asked on the mailing lists and wanted to offer an example solution.

https://gist.github.com/cdrv/5332743

Let me know if you have any comments.
-Kevin

**Comment by eddelbuettel** [comment]
Sounds very promising -- thanks for that.  Am in the middle of something at work and making dinner with kiddo 1 but will get back to this later.

Dirk

**Comment by eddelbuettel** [comment]
It taste like C. Don't we want it more C++-ish? Part of our mantra was that "you can leave C behind".  I feel we should keep that story.

**Comment by kevinushey** [comment]
I thought about it a little harder, and it seems that all we really need (?) is the `TYPEOF` macro from the R API as well as the internal RTYPEs. I cleaned it up and wrote a cleaner, more C++ solution (wrap to List initially, use list iterator, but still switch and wrap depending on the result of `TYPEOF`)

Thanks for the comments -- take a look and let me know!

**Comment by kevinushey** [comment]
I made some more mods (added a check for factors; make sure it gives sensible output when we have character vecs / factors in the list)

I'm not quite sure what you mean re: the default case, can you expand a bit?

**Comment by eddelbuettel** [comment]
Sorry, not "the" default case. Meant to say that we need a fallback "default" case in the switch statement in order to catch errors caused by users submitting a char, or complex, or raw, or environment, or ...    SEXP can be anything beyond int, double or another list.

**Comment by kevinushey** [comment]
Gotcha. I added a default case that just throws a simple exception with `stop` if a non-REALSXP or non-INTSXP is encountered. I also added a bit more exposition, re: what's going on. Thanks!

**Comment by eddelbuettel** [comment]
This is done now, parallel comment threads and all.
