### ISSUE TITLE
"segmentation fault" with a simple testing case

### ISSUE THREAD

**Issue by fasterpython** [RcppCore/rcpp-gallery#32]
Hello, I test Rcpp on Debian/64bit, compiled "Rcpp_test.cpp" without any warnnings.
but got "segmentation fault" when launched.
## It's the most simple case, I just didn't know why. Please help to have a look, much thanks.

//Rcpp_test.cpp
# include "Rcpp.h"

using namespace Rcpp;

int main(int argc, char const\* argv[])
{  
    Rcpp::NumericVector xx(10);  
    return 0;
}

**Comment by eddelbuettel** [comment]
You seem to _completely_ misunderstand what Rcpp is for and how it used.  Maybe you want to start by reading the Rcpp-introduction. 

For embedding R inside of C++ applications we have the related RInside project.

And lastly, this venue is NOT where you should ask for help on Rcpp.  Ever.
