### ISSUE TITLE
Gallery contribution: First Derivative of the Multivariate Normal Densities with RcppArmadillo

### ISSUE THREAD

**Issue by jlegewie** [RcppCore/rcpp-gallery#35]
Here is the [gist with the Rmd file](https://gist.github.com/jlegewie/6485612) following the stackoverflow discussion [here](http://stackoverflow.com/a/18678664/2503795). Let me know if anything is missing.

**Comment by eddelbuettel** [comment]
Nice, thank you -- will take a closer look later.

One thing tough: the dmnorn post is under a pending rewrite as it is _much_ better to supply a decomposed covariance matrix (just using QR, say).  Could you / would you be able to adapt this similarly, either now or once the other post has been updated?

**Comment by jlegewie** [comment]
Yes, I can look into that once the other post has been updated. Feel free to hold this until then and let me know if you have other suggestions.

**Comment by eddelbuettel** [comment]
We can probably post it now; I may add a comment to this effect at the end if that is fine with you.

But off to kiddo's soccer game shortly.

**Comment by jlegewie** [comment]
Yes, of course. Change or add anything. I looked at the `update-dmvnorm-arma` fork. Does that already include the (mostly) finalized changes based on the `lndMvn` approach?

**Comment by eddelbuettel** [comment]
It could have / should have but I just got those by email while I was out.  Will commit there though. [ BTW: That's just a branch, not a fork. ]

**Comment by eddelbuettel** [comment]
I just posted the updated dmvnorm-arma story.  On to yours now :)

**Comment by eddelbuettel** [comment]
Jekyll (the processor invoked to build the site, and which calls knitr on the Rmd files) choked on the equation. I am also not sure we can do the charts--no other posts have any.

**Comment by jjallaire** [comment]
For equations to work I think we'd need two conditions met:

(1) Include the MathJax scripts in our head tag. Basically this:

<script type="text/javascript"
src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

(2) Embed equations using the lower-level MathJax embedding escapes
(including enclosing block tags). For display equations:

<div>
\[   *equation*   \]
</div>

For inline equations:

<span>(  _equation_  )</span>

The <div> and <span> tags are there to cause the markdown processor to
leave what's inside alone.

In theory this should work however there are a lot of tools in play and who
knows if it all comes out the way we expect.

Plots/images indeed don't work (although could certainly be made to work
with a bit more effort).

**Comment by eddelbuettel** [comment]
On a more positive note, on my box the speed gain is around 660-fold and not "just" 400...

**Comment by jlegewie** [comment]
Okay, I have updated the [gist](https://gist.github.com/jlegewie/6485612). It now uses the same algorithm as the most recent version of the dmnorn post. The updated version is actually as fast as the previous one but the R code is faster so that the performance gain is now 300-fold on my machine. I bet you get more maybe because your compiler is better configured. Feel free to add a sentence with your gains. 
I have also removed the formula and the image. I think plots would be nice addition to the rcpp gallery but I can see that it's not at the core of rcpp and therefore secondary.

**Comment by eddelbuettel** [comment]
Nice. I'll post that in a minute after a few smallish edits.

I still get a huge gain. I think it may be the BLAS. Though that should help the R version too. Hm. 

What machine were you running on?  64-bit Linux, 8 cores here.

**Comment by jlegewie** [comment]
I tested it both on my local machine, which is a 2012 Macbook Air, and a computational cluster with 64-bit Linux and lots of cores but I think my session was limited to 4.

**Comment by eddelbuettel** [comment]
I just mod'ed it once more and added butt-ugly  {   }   around the two R code chunks. I think those used to rendered as a single block, but right now it seems I have to force it.  Might be a change in knitr, dunno.

**Comment by eddelbuettel** [comment]
The 'butt-ugly' issue was a knitr / jekyll disconnect we're now fixing...

**Comment by eddelbuettel** [comment]
With that, we can close this -- thanks a lot for the contribution!
