### ISSUE TITLE
Dice coefficient in Rcpp

### ISSUE THREAD

**Issue by bobthecat** [RcppCore/rcpp-gallery#37]
Hello,
I wrote a small article for the Rcpp Gallery following the suggestion of Dirk. The .Rmd file can be found here https://gist.github.com/bobthecat/6509321

Thanks,
David

**Comment by eddelbuettel** [comment]
Quoting from what I commented at the gist::
"Nice. I think we need to a) standardize the tags (just 'eigen') and b) convert the code to use the newer Rcpp attributes (see the corresponding vignette). I can do that quickly if you;d want me to."

Can you alter it? Or do you want me to?

**Comment by bobthecat** [comment]
Hi Dirk,

If you could do it that would be great. I have no idea about the newer Rcpp attributes.

-David

**Comment by eddelbuettel** [comment]
Following a closer look, I have to say that your post has a number of difficiencies:
- You don't actually use Markdown to generate output, it is copied statically.
- When I run the microbenchmark the results are even, not 3-times faster.
- Is there a reason not to write the rest of 'diceR' in C++?

**Comment by bobthecat** [comment]
- I copied the code statically because the C code in the crossprodCpp function throw an error when I transform the document to HTML.
- I re-run the test but copied the text from the Stackoverflow post without looking. If you take the median its 2.3x faster in the latest run. What is in the Gist is what output my machine... I don't understand why you have different results.
- No reason but I can work on making it all C++

I will work on it an submit another Gist

**Comment by eddelbuettel** [comment]
Can you shoot me an email to my usual address?  I can send you what I have -- you can easily convert the .Rmd using knitr (or inside RStudio) -- and that way you'd have a small head-start.

**Comment by eddelbuettel** [comment]
@bobthecat quick ping -- still interested in getting this done?  I (cough, cough) had forgotten how this had fallen to the wayside....

I'd be up for picking it up again.  Pull request preferred, email also possible.  It helps if I can render it first locally.

**Comment by bobthecat** [comment]
Hi Dirk,

Long time indeed. I changed job in the mid time. I will give it a shot ASAP. 

Cheers,
-David

**Comment by eddelbuettel** [comment]
Pinging @bobthecat 

David,  Any chance you'll revisit this in the near future?

**Comment by eddelbuettel** [comment]
Closing this now as it seems to be dead.  Feel free to reopen if there is material.
