### ISSUE TITLE
Dynamic dispatch for sparse matrices

### ISSUE THREAD

**Issue by fabian-s** [RcppCore/rcpp-gallery#47]
Hi,

Dirk asked whether I wanted to write up an entry based on an answer I posted on StackOverflow, here it is:  https://gist.github.com/fabian-s/9665846

Best wishes & thanks for the great work you all are doing with Rcpp,
Fabian

**Comment by eddelbuettel** [comment]
Super -- will look more closely this eve and commit.  You've already won on my number one nag: people tend to invent new tags, and you refrained from that :)

**Comment by eddelbuettel** [comment]
And done -- nice post, I did one minor reindent, so thanks!
