### ISSUE TITLE
Proposed new entry: A simple array class with specialized linear algebra routines

### ISSUE THREAD

**Issue by fabian-s** [RcppCore/rcpp-gallery#48]
Hi,

I wrote up an entry [here](https://gist.github.com/fabian-s/9685081), you can take a look the rendered HTML [here](http://rpubs.com/fabian-s/arraycpp).

I hope it's not too long or math-heavy. Any suggestions on how to improve the code are very much appreciated.

Thank you all for your excellent work,
Fabian

**Comment by eddelbuettel** [comment]
Looks fantastic at first sight -- will fold it in this evening!

**Comment by eddelbuettel** [comment]
One problem, though, is that the Rcpp Gallery is not the same as the RPubs where you placed the html.  As I recall, we don't have Mathjax, so no formulae.  (Correct me if I'm wrong, @jjallaire )

Can you rewrite in 'ascii art' math?

**Comment by jjallaire** [comment]
That's correct, we don't support MathJax on Rcpp Gallery.

J.J.

**Comment by eddelbuettel** [comment]
One cheap-but-ugly way to fudge-rather-than-fix this would be to have the Rcpp Gallery piece point to a companion piece at RPubs or anywhere else.

**Comment by fabian-s** [comment]
I've updated the gist to avoid MathJax -- don't think it's an issue here. The audience at RcppGallery will be familiar with the R commands that I've replaced the formula notation with anyways. 

Again, any pointers you might have on how to improve the code in terms of robustness, efficiency or readability would be very much appreciated.

**Comment by eddelbuettel** [comment]
Now posted. 

Thanks again, and thanks for removing the latex notation we cannot display at the Rcpp Gallery.

**Comment by fabian-s** [comment]
Sure, thank you guys for the great ressources you provide.
