### ISSUE TITLE
Update the dependencies of Local Development Configuration

### ISSUE THREAD

**Issue by wush978** [RcppCore/rcpp-gallery#49]
Hello,

I tried to build the rcpp-gallery locally on ubuntu 13.04 and found some missing dependencies in the https://github.com/jjallaire/rcpp-gallery/wiki/Local-Development-Configuration.

There is 1 more package required to build the project: RcppGSL

Here is my shell script to install the dependencies and R packages:

```
apt-get build-deps r-cran-rgl # sensitivity requires rgl
apt-get install libgsl0-dev libgmp-dev  # RcppGSL requires gsl and some packages requires gmp
```

```

install.packages(c("Rcpp", 
    "RcppEigen", 
    "RcppArmadillo", 
    "RcppProgress", 
    "BcppGSL",
    "xts", 
    "BH", 
    "bigmemory", 
    "knitr", 
    "benchmark", 
    "rbenchmark", 
    "sensitivity"))
```

Hope them help

**Comment by eddelbuettel** [comment]
Thanks, I just added it. 

The point of a wiki being a wiki is that ... everybody can edit it. Next time, feel free to just make a change (unless you feel it is more appropriate to run the change by us first).
