### ISSUE TITLE
2014-06-24-speed-chain-ladder-analysis.cpp

### ISSUE THREAD

**Issue by ActiveAnalytics** [RcppCore/rcpp-gallery#51]
Dear JJ Allaire, please include my article speed chain ladder analysis using Rcpp https://gist.github.com/ActiveAnalytics/27ad99f108a6b0c18787 in the Rcpp gallery

Thanks

Chibisi

**Comment by eddelbuettel** [comment]
Hi Chibisi -- thanks for the submission.  I think some of the comments I made in email after your related blog post still hold so I'd like to iterate over this for a bit. Both JJ and I are traveling today but we'll get back to you "shortly".  Which in this case may mean a day or two. Hope that's ok.

**Comment by ActiveAnalytics** [comment]
Hi Dirk,

Thats fine. I'll make another pass at this and fix it.

Chibisi

**Comment by ActiveAnalytics** [comment]
It is now updated, I think I'll go back to the blog and tweak things there
too.

Thanks

Chibisi

**Comment by eddelbuettel** [comment]
Thanks. I'll probably have to rework this a little to fit our framework and will commit from my edits when I get to it -- maybe later today, maybe tomorrow.

**Comment by eddelbuettel** [comment]
Never closed the issue ticket -- my bad.  Doing so now.
