### ISSUE TITLE
Possible bug in example split_indices function

### ISSUE THREAD

**Issue by jtoll** [RcppCore/rcpp-gallery#66]
While reading through [_posts/2013-12-02-plyr-c-to-rcpp.md](http://gallery.rcpp.org/articles/plyr-c-to-rcpp/) trying to make sense of the C++ code and the intended output of the `split_indices` function, I may have found a small bug.  I ended up running the function to get an idea of the output it generated and was surprised by the result.

Currently, it appears that unless the `IntegerVector x` passed into the function is presorted from min to max, or `n = max(x)`, then the list returned by the function is truncated by `ids.resize(x[i])` to a length that is the value of the final element of `x`. For example, `split_indices(sample(100))` typically results in lists that are less than 100 elements long despite no replacement, whereas `split_indices(sample(100), n = 100)` returns the value I would expect.

I'm not really sure what the intended output is supposed to be, but rather than:

```
if (x[i] > n) {
    ids.resize(x[i]);
 }
```

perhaps the code should be:

```
if (x[i] > ids.size()) {
    ids.resize(x[i]);
}
```

Then the length of `ids` will only be extended via `resize` rather than possibly truncated in the situation where `x[i] > n` but `x[i] < ids.size()`.

Additionally, there are two references to `out` in the second bullet point under the example C++ code which should probably be changed to `ids`.

Thanks

**Comment by eddelbuettel** [comment]
Pinging @hadley....

**Comment by eddelbuettel** [comment]
I agree on the two `out` which should be `ids` and will make that change.  As for the behaviour of the function, I am not so sure: `n` is after all a parameter here.  Also, after 

```
  std::vector<std::vector<int> > ids(n);
```

`n` and `ids.size()` will be the same methinks.

@hadley?

**Comment by jtoll** [comment]
Yes, `std::vector<std::vector<int> > ids(n);` should initially make the length of `ids` the same as the value of `n`.  I think the problem is in the loop where `ids.resize(x[i])` will grow or **shrink** the length of `ids`.

As I said, I'm not sure what kind of input @hadley is expecting to this function. As it currently exists in this example, unless `n=max(x)` then this function truncates and loses data whenever `x[i] > n` but `x[i] < ids.size()`.

Not to seem ungrateful for this article, because in fact I think I learned a lot debugging it, and appreciate the time that went into all the articles.  I would just make the point, as someone who came to this example to try to learn from it, that if the function is in fact written properly, then it might be worthwhile to include a description of the nature of the function inputs (e.g. `n` always equals `max(x)` or `x` is always presorted from min to max).

Thanks for looking into this.

**Comment by hadley** [comment]
I think it should be

``` R
if (x[i] >= ids.size()) {
  ids.resize(x[i]);
}
```

(note the `>=` since if you're inserting element 9 you need a vector of length 10). 

I think the argument `n` is just a performance optimisation - if you know the output size in advance, you can supply it, avoiding any copies.

**Comment by eddelbuettel** [comment]
Could you pretty-please expand the article and provide some illustrative input data and output data?

**Comment by jtoll** [comment]
> (note the `>=` since if you're inserting element 9 you need a vector of length 10).

I don't believe `x[i] >= ids.size()` would cause any problems, other than possible inefficiency, but I don't believe it is actually necessary.  I believe `x[i] > ids.size()` is sufficient to fix the problem.

If x[i] == 9, then you would `push_back` `i+1` to `ids[x[i] - 1]`.  A length of 9 is sufficient, but the max index of ids would be 8.  You should only need to resize if `x[i] > ids.size()`.  I believe Rcpp must automatically convert the 0-based vector indices to 1-based indices when brought back in to R.

**Comment by eddelbuettel** [comment]
> I believe Rcpp must automatically convert the 0-based vector indices to 1-based indices when  brought back in to R.

It is much less mysterious.  Any C/C++ vector goes from 0 to n-1, and in R it will always be 1 to n.  That's ensured by the respective language specification; not need for Rcpp to do anything.

**Comment by eddelbuettel** [comment]
@jtoll @hadley 

Where are we on this?  Bug?  No bug?  Change needed, or not?   

Follow-up appreciated.

**Comment by jtoll** [comment]
I'm not sure of the status.  I think there is consensus that this is a bug, but possibly a slight difference of opinion on how to fix.  I interpreted your "pretty-please expand the article" as being directed at @hadley.

As an aside, this same code currently appears in `plyr` and therefore probably needs to be fixed there as well.  Wondering if I should open a separate bug report there so it doesn't get forgotten.

https://github.com/hadley/plyr/blob/master/src/split-numeric.cpp

**Comment by hadley** [comment]
I'm aware of the problem (both here and in plyr), so no need to file another bug elsewhere.

**Comment by eddelbuettel** [comment]
@hadley that does not answer my (earlier) question.

**Comment by hadley** [comment]
@eddelbuettel as I told you via IM, I will prepare a PR

**Comment by eddelbuettel** [comment]
Thanks.
