### ISSUE TITLE
parallel-vector-sum: broken link (404) to parallel-matrix-transform

### ISSUE THREAD

**Issue by MattPD** [RcppCore/rcpp-gallery#73]
Hi!

First of all, thank you for the library and the Rcpp Gallery articles!

While reading I've noticed that there's a broken link in the "Parallel Version" section of the `parallel-vector-sum` article: http://gallery.rcpp.org/articles/parallel-vector-sum/#parallel-version

Namely, attempting to follow the `previous article` hyperlink leads to the following URL (resulting in a 404): http://gallery.rcpp.org/articles/parallel-vector-sum/2014-06-29-parallel-matrix-transform.cpp

Seems too trivial for a PR (I presume? just in case, I'm going to make one, too), so here's a proposed fix:
- change this line: https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/src/2014-06-29-parallel-vector-sum.cpp#L37
- from: `[previous article](2014-06-29-parallel-matrix-transform.cpp)`
- to: `[previous article](http://gallery.rcpp.org/articles/parallel-matrix-transform/)` 

/*

Following the working example at: https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/src/2014-07-15-parallel-inner-product.cpp
which links to: https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/src/2014-06-29-parallel-vector-sum.cpp
living at: http://gallery.rcpp.org/articles/parallel-vector-sum/
using: `[parallel-vector-sum](http://gallery.rcpp.org/articles/parallel-vector-sum/)`

Comparing: https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/src/2014-06-29-parallel-vector-sum.cpp
which attempts to link to: https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/src/2014-06-29-parallel-matrix-transform.cpp
living at: http://gallery.rcpp.org/articles/parallel-matrix-transform/
using: `[previous article](2014-06-29-parallel-matrix-transform.cpp)`

*/

**Comment by eddelbuettel** [comment]
Looks like this got fixed in in #74 -- thanks again!
