### ISSUE TITLE
"Versioning" articles / showing old approaches

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/rcpp-gallery#78]
I made RcppGSL better in the summer--no more explicit `free()` on the objects etc pp so I should update the three posts.  I can't quite figure out what I want:  just the new (better) approach?   New and old for comparison?   Thoughs...

**Comment by jjallaire** [comment]
I'd go with just the new approach so as to not create ambiguity about what
the right way is.

On Thu, Nov 12, 2015 at 2:38 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Right on.  That is a fair point.

**Comment by eddelbuettel** [comment]
Done [for the first GSL piece](http://gallery.rcpp.org/articles/gsl-colnorm-example/)

@jjallaire Take a quick peek at it and at the top.  Is there a clever jekyll / css way put the 'edited on' line up in the little header that precedes it?  Ie have something in yaml, and show if present but skip if not?

**Comment by jjallaire** [comment]
Right now we don't have arbitrary passthrough of @ fields to YAML so we'd
have to add code to the knit script to make this work (then we'd also do
some if/then in the jekyll template). If this is only for a few articles
probably easiest to just hard code the header.

On Sat, Nov 21, 2015 at 9:42 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Fair (but I meant from YAML to md).  Could one override the line showing 

> Dirk Eddelbuettel — Dec 22, 2012 | source

I'd love something like 

> Dirk Eddelbuettel — Dec 22, 2012 (updated Nov 21, 2015) | source

We could even add custom code there -- I am just asking because I hardly know Jekyll and Ruby.

The manual line below it surely works.

**Comment by jjallaire** [comment]
Right now though in our C++ source files we convert @ fields to YAML fields
explicitly, so we would need to update that script to automatically forward
all @ fields into YAML.

On Sat, Nov 21, 2015 at 1:25 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Would it be easier from Rmd?

I am also thinking to kill the .cpp and make it all .Rmd.  Or one by one...

**Comment by jjallaire** [comment]
Yeah I think Rmd already has YAML so it would indeed be easier.

But none of this is hard, just requires ~ 60 minutes of hacking around that
I don't have just now :-\

On Sat, Nov 21, 2015 at 1:27 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
I can take a peek sometime.  Pointers would help, or maybe I just poke.  Sadly I do not know the ruby equivalent of `if (exist("var")` but this really is the opposite of urgent...

**Comment by jjallaire** [comment]
Taking another look at the code I realized that @ fields are automatically
forwarded into front matter. So it should just be a matter of adding an
"updated" field and then checking for it's existence here:

https://github.com/RcppCore/rcpp-gallery/blob/gh-pages/_layouts/post.html#L7

Something like:

{% if page.updated %} whatever you want to generate {% endif %}

On Sat, Nov 21, 2015 at 1:40 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Let me give that a spin in branch.

I should also be able to just rework a `source/date-title.cpp` into `source/date-title.Rmd` --- while obviously changing the content as well --- as both are pre-processed by us before Jekyll see them, correct?

**Comment by eddelbuettel** [comment]
**Love it** 

PR coming in a second.
