### ISSUE TITLE
CSS update?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/rcpp-gallery#84]
Maybe it was the last Jekyll update at GitHub ... but right now the rendered pages look suboptimal:
- The font is too small
- We may want to pick a clearer webfont
- The code blocks and output have different indentations.  Is that a knitr issue?

I am not much of a CSS writer.  Can we get help?    Ideas, @jjallaire -- maybe calling out to @yihui ?

**Comment by jjallaire** [comment]
I tweaked the font size and the code block indentation. Let me know what
you think.

On Tue, May 17, 2016 at 8:28 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Rock star material!

Thank you so much.  That had been bugging me for a bit....
