### ISSUE TITLE
Submitting two articles: HRP and Gerber

### ISSUE THREAD

**Issue by nextlevelanalytics** [RcppCore/rcpp-gallery#85]
Hello,

I suggest adding these two articles to the Rcpp gallery: 
1. http://nextlevelanalytics.github.io/2016/05/27/HRP/
2. http://nextlevelanalytics.github.io/2016/05/26/Gerber/

The markdowns can be found here: https://github.com/nextlevelanalytics/nextlevelanalytics.github.io/tree/master/_posts

Thanks

**Comment by jjallaire** [comment]
Could we get these as Rmd rather than .md (that we we can re-execute the
code). Here are the guidelines for submitting articles:
https://github.com/RcppCore/rcpp-gallery/wiki/Contributing-to-the-Rcpp-Gallery

**Comment by nextlevelanalytics** [comment]
Hi sorry about that, Below are the two Rmd files:

HRP: https://github.com/nextlevelanalytics/nextlevelanalytics.github.io/tree/master/RMD/HRP
Gerber: https://github.com/nextlevelanalytics/nextlevelanalytics.github.io/tree/master/RMD/Gerber

Thanks!

**Comment by eddelbuettel** [comment]
Sorry to bug you some more but could you possibly submit them as pull requests as outlined in the reference JJ gave?

**Comment by eddelbuettel** [comment]
Looks good otherwise, and I do of course have a soft spot for the Finance content---and Open MP is always welcome too.  One stylistic note: the ALLUPPERCASE variable names (in HRP) are a little uncommon...

**Comment by nextlevelanalytics** [comment]
I have submitted the pull request, please let me know if you need me to do anything else.

**Comment by nextlevelanalytics** [comment]
I have one question, for example in Gerber, is it possible to style the tables such that it looks like the tables at http://nextlevelanalytics.github.io/2016/05/26/Gerber/ ? Scroll to the bottom of the page to see the table (Implementation ... replications .. elapsed .. relative)

**Comment by eddelbuettel** [comment]
These are both in (but still may need more editorial polish; maybe I get to it.

I'll also try re-running these on a machine with more cores to have OpenMP shine some more.
