### ISSUE TITLE
Rcpp::StringVector

### ISSUE THREAD

**Issue by knausb** [RcppCore/rcpp-gallery#93]
Hello,

Over the last year or so I've been trying to teach myself Rcpp and C++. At some point I made my own cheat sheet and at some point I thought to format it for the Rcpp Gallery in case people thought it may be an appropriate contribution. You can find it here:

[Rcpp::StringVector](https://gist.github.com/knausb/a9f6a70931607038a5a2)

Is this the sort of material you would like to include in your gallery? Have I learned reasonable ways of working with Rcpp?

Thank you!
Brian

**Comment by eddelbuettel** [comment]
Hi Brian,

Thanks for getting in touch.  Contributions are generally a pull request of a .Rmd or .cpp file (see the contributing hints).   The current contributions have a sort-of consistent style -- something about string vector would be welcome.  Can you transform it into a pull request?

Thanks, Dirk

**Comment by knausb** [comment]
This issue has been changed to a pull request. See #94 and #95.
