### ISSUE TITLE
Updating Armadillo Subset

### ISSUE THREAD

**Issue by coatless** [RcppCore/rcpp-gallery#98]
Possibly update the [Armadillo subset](http://gallery.rcpp.org/articles/armadillo-subsetting/) post with:
1. non-contiguous view extraction (see: http://stackoverflow.com/questions/38541787/change-elements-at-given-positions-in-an-armavec-with-corresponding-elements-i)
2. use of [sub2ind](http://arma.sourceforge.net/docs.html#sub2ind) and [ind2sub](http://arma.sourceforge.net/docs.html#ind2sub)
3. direct hints at http://arma.sourceforge.net/docs.html#submat

**Comment by eddelbuettel** [comment]
That would be awesome as this is a popular topic.  Do you have time and energy to take a lead?

**Comment by coatless** [comment]
@eddelbuettel PR is planned for tomorrow.

**Comment by coatless** [comment]
@eddelbuettel 

Okay to convert the `2013-01-02-armadillo-subsetting.cpp` to an RMarkdown file?  Or would you prefer a _new_ post?

**Comment by eddelbuettel** [comment]
Or just an amended/extended post?  

I am torn between the `.Rmd` and `.cpp` formats as they both work.   Maybe just maybe we do need to convert all the `.cpp` in an eventual conversion to bookdown but so far I saw no need.

I'd say whatever you find easiest.  If it were me I'd just add two paragraphs.  But see how it goes.  No real reason _not_ to have a new post if you have enough to say.   Ok?
